### ISSUE TITLE
Wrong message generation for updateSecret method

### ISSUE THREAD

**Issue by kadhaus** [Gurux/Gurux.DLMS.Python#23]
When you generate a message with updateSecret method `(class_id = 15, ln = 0.0.40.0.0.255)` you add to message the secret itself. As I can found in DLMS that method require AES-128 ciphered secret, where key is old secret. Check it out, please. I reference to russian implementation of DLMS - SPODES (СПОДЭС), but I hope you have a complete Green Book, and can check it with that book.

**Comment by gurux-kurumi** [comment]
Hi, 

Please, create issues to Gurux forum. I'm not read Github issues and I just received information from this. 

updateSecret sends plain octet-string because AES-128 ciphered secret is added later and older meters don't use it. This is defined in the Blue Book.
You can generate AES-128 ciphered secret with GXDLMSSecureClient.Encrypt method and then send generated secret with updateSecret method.

BR,
Mikko
